[package]
name = "scope-tui"
version = "0.2.1"
edition = "2021"
authors = [ "alemi <me@alemi.dev>" ]
description = "A simple oscilloscope/vectorscope for the terminal, inspired by cava"
keywords = ["tui", "terminal", "audio", "visualization", "scope", "dashboard"]
repository = "https://github.com/alemidev/scope-tui"
readme = "README.md"
# documentation =
# license = 


[dependencies]
tui = "0.19"
crossterm = "0.25"
libpulse-binding = "2.0"
libpulse-simple-binding = "2.25"
clap = { version = "4.0.32", features = ["derive"] }
